import type { AppLocale, ShareTemplate } from "@/lib/app-ladder";

export const sections = [
  { id: "today", key: "today" },
  { id: "review", key: "review" },
  { id: "ladder", key: "ladder" },
  { id: "share", key: "share" },
] as const;

export const shareOptions: { id: ShareTemplate; key: "shareSTier" | "shareTop3" | "shareHiddenGem" }[] =
  [
    { id: "s-tier", key: "shareSTier" },
    { id: "top-3", key: "shareTop3" },
    { id: "hidden-gem", key: "shareHiddenGem" },
  ];

export const uiCopy = {
  en: {
    nav: { today: "Today", review: "Review", ladder: "Ladder", share: "Share" },
    heroEyebrow: "Daily editorial board",
    heroTitle:
      "A quieter daily miniapp journal, with your private tier board underneath.",
    heroText:
      "The structure stays playful, but the surface is calmer: more room, cleaner type, and a portfolio-like editorial rhythm.",
    todayPick: "Today's one pick",
    startReview: "Start today's review",
    openShare: "Open share studio",
    currentSession: "Current session",
    guest: "Guest collector",
    guestCopy: "No login required for the MVP core loop",
    detectSurface: "Detecting surface",
    statuses: { today: "Today", streak: "Streak", board: "Board" },
    noReview: "No review yet",
    locked: (tier: string) => `${tier} tier locked`,
    days: (count: number) => `${count} day`,
    reviews: (count: number) => `${count} reviews`,
    config: { appUrl: "App URL", appId: "Base App ID", surface: "Surface", dayKey: "Day key" },
    today: {
      kicker: "Today",
      title: "A daily loop with more breathing room",
      body: "Pick one app, leave a short review, and let the board grow at a human pace.",
      target: "Today's review target",
      status: "Daily status",
      recent: "Recent reviews",
      openTitle: "Today is still open",
      openBody: "You have not saved a review for this day yet. Pick one app and pin it to the board.",
      noReviewsTitle: "No reviews yet",
      noReviewsBody: "Your first review will unlock the recent activity strip here.",
      noShortNote: "No short note yet.",
      freshlyRanked: "Freshly ranked.",
      savedToday: (tier: string) => `${tier} tier saved today`,
    },
    review: {
      kicker: "Review",
      title: "A five minute review studio",
      body: "Browse the static miniapp set, choose today's candidate, and save one private rating for this day.",
      selected: "Selected miniapp",
      external: "Open external link",
      tier: "Tier",
      shortNote: "Short note",
      placeholder: "What made this one stick with you today?",
      save: "Save today's review",
      saved: (name: string, dayKey: string) => `${name} was pinned to your board for ${dayKey}.`,
      fun: "Fun",
      polish: "Polish",
      comeBack: "Come back",
    },
    ladder: {
      kicker: "Ladder",
      title: "A private tier board with lighter framing",
      body: "Filter by category, switch the order, and keep the latest review per miniapp as the board truth.",
      all: "All",
      newest: "Newest first",
      oldest: "Oldest first",
      emptyTitle: (tier: string) => `No ${tier} tier yet`,
      emptyBody: "A saved review will drop a sticker here.",
      noNote: "Boarded without a note.",
    },
    share: {
      kicker: "Share",
      title: "A simpler share card studio",
      body: "Preview a tall card, export a PNG, and copy a short cast line without leaving the app.",
      shareSTier: "This week's S tier",
      shareTop3: "Top 3",
      shareHiddenGem: "Hidden gem",
      savePng: "Save PNG",
      copy: "Copy cast text",
      copied: "Share copy copied.",
      blocked: "Clipboard copy was blocked in this environment.",
      notReady: "Share card preview is not ready yet.",
      pngSaved: "PNG saved from the share preview.",
      pngFailed: "PNG export failed in this browser.",
      cardTitle: "Private Base miniapp tier list",
      cardCount: (count: number, streak: number) => `${count} apps ranked with a ${streak}-day streak.`,
      cardEmpty: "Start reviewing to generate your first board card.",
      nothingTitle: "Nothing ranked yet",
      nothingBody: "The share card will fill itself from your saved reviews.",
      noNote: "Pinned without a note.",
      footerLeft: "base + farcaster + browser",
      footerRight: "solo collection mode",
    },
    weekly: {
      kicker: "Weekly",
      title: "S tier roundup",
      body: "Last 7 days of S-tier hits, ready for a share card and cast caption.",
      emptyTitle: "No S tier this week",
      emptyBody: "Once something really lands, it will surface here for sharing.",
      noNote: "No note attached yet.",
    },
    loadError:
      "Local data could not be read. You can keep reviewing, but older entries might be unavailable until storage is reset.",
    dismiss: "Dismiss",
    footerLoaded:
      "English is the default, Japanese is one tap away, and the visual tone is now calmer while the full App Ladder flow stays intact.",
    footerLoading: "Loading local board data...",
    inspectManifest: "Inspect manifest",
  },
  ja: {
    nav: { today: "今日", review: "レビュー", ladder: "ラダー", share: "共有" },
    heroEyebrow: "デイリー・エディトリアル・ボード",
    heroTitle: "落ち着いた誌面トーンで続ける、毎日の miniapp ジャーナル。",
    heroText: "遊び心は残しつつ、余白とタイポを効かせて静かなポートフォリオ感を部分導入しました。",
    todayPick: "今日の1本",
    startReview: "今日のレビューを始める",
    openShare: "共有スタジオを開く",
    currentSession: "現在のセッション",
    guest: "ゲストコレクター",
    guestCopy: "MVP の主機能はログインなしで使えます",
    detectSurface: "表示面を判定中",
    statuses: { today: "今日", streak: "連続", board: "ボード" },
    noReview: "まだ未レビュー",
    locked: (tier: string) => `${tier} tier を保存済み`,
    days: (count: number) => `${count} 日`,
    reviews: (count: number) => `${count} 件`,
    config: { appUrl: "App URL", appId: "Base App ID", surface: "表示面", dayKey: "Day key" },
    today: {
      kicker: "今日",
      title: "余白を持たせたデイリーループ",
      body: "1本選び、短い感想を残し、少しずつボードを育てます。",
      target: "今日のレビュー対象",
      status: "今日の状態",
      recent: "最近のレビュー",
      openTitle: "今日はまだ空いています",
      openBody: "この日のレビューはまだ保存されていません。1本選んでボードに貼ってください。",
      noReviewsTitle: "まだレビューがありません",
      noReviewsBody: "最初のレビューを保存すると、ここに最近の履歴が出ます。",
      noShortNote: "まだ一言メモはありません。",
      freshlyRanked: "今つけたばかりの評価です。",
      savedToday: (tier: string) => `今日は ${tier} tier を保存済み`,
    },
    review: {
      kicker: "レビュー",
      title: "5分レビュー入力",
      body: "静的カタログから1本選び、この日に対する自分だけの評価を保存します。",
      selected: "選択中の miniapp",
      external: "外部リンクを開く",
      tier: "Tier",
      shortNote: "ひとことメモ",
      placeholder: "今日は何が刺さったかを短く残してください。",
      save: "今日のレビューを保存",
      saved: (name: string, dayKey: string) => `${name} を ${dayKey} のボードに保存しました。`,
      fun: "Fun",
      polish: "Polish",
      comeBack: "Come back",
    },
    ladder: {
      kicker: "ラダー",
      title: "静かめトーンのプライベート tier board",
      body: "カテゴリで絞り込み、並び順を切り替え、最新レビューをボードの正として扱います。",
      all: "すべて",
      newest: "新しい順",
      oldest: "古い順",
      emptyTitle: (tier: string) => `${tier} tier はまだありません`,
      emptyBody: "レビューを保存するとここにステッカーが入ります。",
      noNote: "メモなしで追加されました。",
    },
    share: {
      kicker: "共有",
      title: "共有カードスタジオ",
      body: "縦長カードをプレビューし、PNG を保存し、Cast 用の短文をコピーできます。",
      shareSTier: "今週の S tier",
      shareTop3: "Top 3",
      shareHiddenGem: "隠れ良作",
      savePng: "PNG 保存",
      copy: "Cast 文をコピー",
      copied: "共有文をコピーしました。",
      blocked: "この環境ではクリップボードコピーがブロックされました。",
      notReady: "共有カードのプレビューはまだ準備できていません。",
      pngSaved: "共有プレビューから PNG を保存しました。",
      pngFailed: "このブラウザでは PNG 書き出しに失敗しました。",
      cardTitle: "私の Base miniapp tier list",
      cardCount: (count: number, streak: number) => `${count} 本を評価済み。現在 ${streak} 日連続レビュー中。`,
      cardEmpty: "レビューを保存すると、ここに最初のカードが生成されます。",
      nothingTitle: "まだランキングがありません",
      nothingBody: "共有カードは保存済みレビューから自動で埋まります。",
      noNote: "メモなしで保存されました。",
      footerLeft: "base + farcaster + browser",
      footerRight: "solo collection mode",
    },
    weekly: {
      kicker: "週間",
      title: "S tier まとめ",
      body: "直近7日間の S tier を、共有カードや Cast 文に使いやすい形で表示します。",
      emptyTitle: "今週の S tier はまだありません",
      emptyBody: "本当に刺さる1本が出ると、ここに浮かび上がります。",
      noNote: "まだメモはありません。",
    },
    loadError:
      "ローカルデータの読み込みに失敗しました。レビューは続けられますが、過去データはストレージを整理するまで見えない場合があります。",
    dismiss: "閉じる",
    footerLoaded:
      "英語を既定表示にしつつ、日本語にも切り替え可能にしました。見た目は少し静かに寄せています。",
    footerLoading: "ローカルボードのデータを読み込んでいます...",
    inspectManifest: "manifest を確認",
  },
} as const satisfies Record<AppLocale, Record<string, unknown>>;
