import type { AppLocale, ShareTemplate } from "@/lib/app-ladder";

export const sections = [
  { id: "today", key: "today" },
  { id: "review", key: "review" },
  { id: "ladder", key: "ladder" },
  { id: "share", key: "share" },
] as const;

export const shareOptions: { id: ShareTemplate; key: "shareSTier" | "shareTop3" | "shareHiddenGem" }[] =
  [
    { id: "s-tier", key: "shareSTier" },
    { id: "top-3", key: "shareTop3" },
    { id: "hidden-gem", key: "shareHiddenGem" },
  ];

export const uiCopy = {
  en: {
    nav: { today: "Today", review: "Review", ladder: "Ladder", share: "Share" },
    heroEyebrow: "Daily editorial board",
    heroTitle: "Make your own miniapp tier board, then share it.",
    heroText:
      "Save the miniapps you want to track, shape them into a personal tier list, and export a shareable board whenever you want.",
    todayPick: "Today's registered pick",
    startReview: "Register or review today",
    openShare: "Open share studio",
    currentSession: "Current session",
    guest: "Guest collector",
    guestCopy: "No login required for the MVP core loop",
    detectSurface: "Detecting surface",
    statuses: { today: "Today", streak: "Streak", board: "Board" },
    noReview: "No review yet",
    locked: (tier: string) => `${tier} tier locked`,
    days: (count: number) => `${count} day`,
    reviews: (count: number) => `${count} reviews`,
    config: { appUrl: "App URL", appId: "Base App ID", surface: "Surface", dayKey: "Day key" },
    today: {
      kicker: "Today",
      title: "Your shelf, one miniapp at a time",
      body: "Register the miniapps you care about, then review one each day and let the board settle into your own pattern.",
      target: "Today's review target",
      status: "Daily status",
      recent: "Recent reviews",
      emptyPickTitle: "No miniapps registered yet",
      emptyPickBody: "Add your first miniapp with an image URL, public URL, and name to start the daily loop.",
      openTitle: "Today is still open",
      openBody: "You have not saved a review for this day yet. Pick one of your registered miniapps and pin it to the board.",
      noReviewsTitle: "No reviews yet",
      noReviewsBody: "Your first review will unlock the recent activity strip here.",
      noShortNote: "No short note yet.",
      freshlyRanked: "Freshly ranked.",
      savedToday: (tier: string) => `${tier} tier saved today`,
    },
    review: {
      kicker: "Review",
      title: "Register your miniapps, then review them",
      body: "Save the image URL, public link, and name for each miniapp you want to track, then use the same review flow for all of them.",
      searchLabel: "Search your miniapps",
      searchPlaceholder: "Search by name, category, or description",
      catalogCount: (visible: number, total: number) =>
        `${visible} visible out of ${total} saved miniapps.`,
      noMatchesTitle: "No saved miniapps match this search",
      noMatchesBody: "Try a shorter query, or register another miniapp below.",
      selected: "Selected miniapp",
      selectedEmptyTitle: "Nothing selected yet",
      selectedEmptyBody: "Register a miniapp first, or choose one from your saved shelf to start reviewing.",
      external: "Open external link",
      addAnyTitle: "Register a miniapp",
      addAnyBody:
        "Save the image URL, public link, and name for any miniapp you want to review. Category and note are optional helpers.",
      imageLabel: "Image URL",
      imagePlaceholder: "https://.../cover.png",
      urlLabel: "Public link",
      urlPlaceholder: "https://...",
      autofill: "Autofill from URL",
      autofillLoading: "Autofilling...",
      autofillSuccess: "Name, image, and description were filled from the URL.",
      autofillFailed: "Could not read metadata from this URL. You can still enter details manually.",
      autofillInvalid: "Enter a public miniapp URL first.",
      nameLabel: "Name",
      namePlaceholder: "Miniapp name",
      categoryLabel: "Category",
      categoryPlaceholder: "Games, Social, Utility...",
      descriptionLabel: "Short description",
      descriptionPlaceholder: "What does this miniapp do?",
      addAny: "Save to my shelf",
      addAnySaved: (name: string) => `${name} is now on your shelf and ready to review.`,
      addAnyExists: (name: string) => `${name} is already on your shelf.`,
      addAnyInvalid: "Enter a miniapp name, image URL, and valid public URL.",
      deleteAction: "Delete",
      deleteConfirm: (name: string) =>
        `Delete ${name} from your shelf? Its saved reviews will also be removed.`,
      deleteDone: (name: string) => `${name} was deleted from your shelf.`,
      deleteMissing: "That miniapp is already gone.",
      tier: "Tier",
      shortNote: "Short note",
      placeholder: "What made this one stick with you today?",
      save: "Save today's review",
      saveDisabled: "Register or select a miniapp first",
      saved: (name: string, dayKey: string) => `${name} was pinned to your board for ${dayKey}.`,
      fun: "Fun",
      polish: "Polish",
      comeBack: "Come back",
    },
    ladder: {
      kicker: "Ladder",
      title: "A private tier board with your own miniapp shelf behind it",
      body: "Filter by category, switch the order, and keep the latest review per miniapp as the board truth.",
      all: "All",
      newest: "Newest first",
      oldest: "Oldest first",
      deleteAction: "Remove",
      deleteConfirm: (name: string) =>
        `Remove ${name} from the current board? The miniapp will stay on your shelf.`,
      deleteDone: (name: string) => `${name} was removed from the current board.`,
      deleteMissing: "That board entry is already gone.",
      emptyTitle: (tier: string) => `No ${tier} tier yet`,
      emptyBody: "A saved review will drop a sticker here.",
      noNote: "Boarded without a note.",
    },
    share: {
      kicker: "Share",
      title: "A simpler share card studio",
      body: "Preview a tall card, export a PNG, and copy a short cast line without leaving the app. Top 3 shares can bundle up to three miniapps at once.",
      shareSTier: "This week's S tier",
      shareTop3: "Top 3 (up to 3)",
      shareHiddenGem: "Hidden gem",
      savePng: "Save PNG",
      copy: "Copy cast text",
      copied: "Share copy copied.",
      blocked: "Clipboard copy was blocked in this environment.",
      notReady: "Share card preview is not ready yet.",
      pngSaved: "PNG saved from the share preview.",
      pngFailed: "PNG export failed in this browser.",
      cardTitle: "Private Base miniapp tier list",
      cardCount: (count: number, streak: number) => `${count} apps ranked with a ${streak}-day streak.`,
      cardEmpty: "Start reviewing to generate your first board card.",
      nothingTitle: "Nothing ranked yet",
      nothingBody: "The share card will fill itself from your saved reviews.",
      noNote: "Pinned without a note.",
      footerLeft: "base + farcaster + browser",
      footerRight: "solo collection mode",
    },
    weekly: {
      kicker: "Weekly",
      title: "S tier roundup",
      body: "Last 7 days of S-tier hits, ready for a share card and cast caption.",
      emptyTitle: "No S tier this week",
      emptyBody: "Once something really lands, it will surface here for sharing.",
      noNote: "No note attached yet.",
    },
    loadError:
      "Local data could not be read. You can keep reviewing, but older entries might be unavailable until storage is reset.",
    dismiss: "Dismiss",
    footerLoaded:
      "English is the default, Japanese is one tap away, and the whole flow now starts from the miniapps you register yourself.",
    footerLoading: "Loading local board data...",
    inspectManifest: "Inspect manifest",
  },
  ja: {
    nav: { today: "今日", review: "レビュー", ladder: "ラダー", share: "共有" },
    heroEyebrow: "デイリー・エディトリアル・ボード",
    heroTitle: "miniapp の tier 表を作って、共有できる。",
    heroText:
      "気になる miniapp を登録して自分だけの tier 表を作り、好きなタイミングで共有カードとして見せられます。",
    todayPick: "今日の登録済み pick",
    startReview: "登録して今日のレビューへ",
    openShare: "共有スタジオを開く",
    currentSession: "現在のセッション",
    guest: "ゲストコレクター",
    guestCopy: "MVP の主機能はログインなしで使えます",
    detectSurface: "表示面を確認中",
    statuses: { today: "今日", streak: "連続", board: "ボード" },
    noReview: "まだレビューなし",
    locked: (tier: string) => `${tier} tier を保存済み`,
    days: (count: number) => `${count}日`,
    reviews: (count: number) => `${count}件`,
    config: { appUrl: "App URL", appId: "Base App ID", surface: "表示面", dayKey: "Day key" },
    today: {
      kicker: "今日",
      title: "自分の棚から、1日1本ずつ",
      body: "気になる miniapp を自分で登録して、毎日1本レビューしながら、自分だけの board を育てていきます。",
      target: "今日のレビュー対象",
      status: "今日の状態",
      recent: "最近のレビュー",
      emptyPickTitle: "まだ miniapp が登録されていません",
      emptyPickBody: "最初の miniapp を登録すると、画像つきで今日の review loop が始まります。",
      openTitle: "今日はまだ空いています",
      openBody: "この日のレビューはまだ保存されていません。登録済みの miniapp から1本選んでボードに貼りましょう。",
      noReviewsTitle: "まだレビューがありません",
      noReviewsBody: "最初のレビューを保存すると、ここに最近の動きが並びます。",
      noShortNote: "まだひとことメモはありません。",
      freshlyRanked: "さっき順位をつけました。",
      savedToday: (tier: string) => `今日は ${tier} tier を保存済み`,
    },
    review: {
      kicker: "レビュー",
      title: "miniapp を登録してからレビューする",
      body: "レビューしたい miniapp の画像 URL、公開リンク、名前を保存し、そのまま同じレビュー導線で評価できます。",
      searchLabel: "登録した miniapp を探す",
      searchPlaceholder: "名前、カテゴリ、説明で検索",
      catalogCount: (visible: number, total: number) => `${visible}件表示中 / 保存済み ${total}件`,
      noMatchesTitle: "一致する保存済み miniapp がありません",
      noMatchesBody: "検索語を短くするか、下から別の miniapp を登録してください。",
      selected: "選択中の miniapp",
      selectedEmptyTitle: "まだ何も選ばれていません",
      selectedEmptyBody: "先に miniapp を登録するか、保存済みの miniapp を選ぶとレビューできます。",
      external: "外部リンクを開く",
      addAnyTitle: "miniapp を登録",
      addAnyBody:
        "レビューしたい miniapp の画像 URL、公開リンク、名前を保存します。カテゴリと説明は補助情報として任意入力です。",
      imageLabel: "画像 URL",
      imagePlaceholder: "https://.../cover.png",
      urlLabel: "公開リンク",
      urlPlaceholder: "https://...",
      autofill: "URL から自動入力",
      autofillLoading: "自動入力中...",
      autofillSuccess: "URL から名前、画像、説明を自動入力しました。",
      autofillFailed: "この URL から metadata を取得できませんでした。手入力はそのまま可能です。",
      autofillInvalid: "先に公開 URL を入力してください。",
      nameLabel: "名前",
      namePlaceholder: "miniapp 名",
      categoryLabel: "カテゴリ",
      categoryPlaceholder: "Games / Social / Utility など",
      descriptionLabel: "短い説明",
      descriptionPlaceholder: "この miniapp でできることを一言で",
      addAny: "自分の棚に保存",
      addAnySaved: (name: string) => `${name} を棚に保存しました。すぐレビューできます。`,
      addAnyExists: (name: string) => `${name} はすでに棚にあります。`,
      addAnyInvalid: "miniapp 名、画像 URL、公開 URL を入力してください。",
      deleteAction: "削除",
      deleteConfirm: (name: string) =>
        `${name} を棚から削除しますか？ 保存済みレビューも一緒に消えます。`,
      deleteDone: (name: string) => `${name} を棚から削除しました。`,
      deleteMissing: "その miniapp はすでに削除されています。",
      tier: "Tier",
      shortNote: "ひとことメモ",
      placeholder: "今日は何が刺さったかを書いてください。",
      save: "今日のレビューを保存",
      saveDisabled: "先に miniapp を登録または選択してください",
      saved: (name: string, dayKey: string) => `${name} を ${dayKey} のボードに保存しました。`,
      fun: "Fun",
      polish: "Polish",
      comeBack: "Come back",
    },
    ladder: {
      kicker: "ラダー",
      title: "自分の miniapp 棚から育つ private tier board",
      body: "カテゴリで絞り込み、並び順を変え、miniapp ごとの最新レビューをボードの真実として扱います。",
      all: "すべて",
      newest: "新しい順",
      oldest: "古い順",
      deleteAction: "外す",
      deleteConfirm: (name: string) =>
        `${name} を今回の board から外しますか？ miniapp の登録自体は残ります。`,
      deleteDone: (name: string) => `${name} を今回の board から外しました。`,
      deleteMissing: "その board entry はすでにありません。",
      emptyTitle: (tier: string) => `${tier} tier はまだありません`,
      emptyBody: "レビューを保存すると、ここにステッカーが落ちます。",
      noNote: "メモなしで保存されました。",
    },
    share: {
      kicker: "共有",
      title: "共有カードスタジオ",
      body: "縦長カードをプレビューし、PNG を保存して、Cast 用の短文もその場でコピーできます。Top 3 は miniapp を3つまでまとめて共有できます。",
      shareSTier: "今週の S tier",
      shareTop3: "Top 3（最大3つ）",
      shareHiddenGem: "隠れ推し",
      savePng: "PNG 保存",
      copy: "Cast 文をコピー",
      copied: "共有文をコピーしました。",
      blocked: "この環境ではクリップボードへのコピーがブロックされました。",
      notReady: "共有カードのプレビューはまだ準備できていません。",
      pngSaved: "共有カードを PNG で保存しました。",
      pngFailed: "このブラウザでは PNG 書き出しに失敗しました。",
      cardTitle: "私の Base miniapp tier list",
      cardCount: (count: number, streak: number) => `${count}本を評価済み。連続レビューは ${streak}日です。`,
      cardEmpty: "レビューを始めると、最初の共有カードが生成されます。",
      nothingTitle: "まだランキングがありません",
      nothingBody: "保存したレビューが増えると、共有カードが自動で埋まります。",
      noNote: "メモなしで保存。",
      footerLeft: "base + farcaster + browser",
      footerRight: "solo collection mode",
    },
    weekly: {
      kicker: "週間",
      title: "S tier まとめ",
      body: "直近7日間の S tier を並べて、共有カードや Cast 文にすぐ使える形で見せます。",
      emptyTitle: "今週の S tier はまだありません",
      emptyBody: "強く刺さる1本が出ると、ここに浮かび上がります。",
      noNote: "まだメモはありません。",
    },
    loadError:
      "ローカルデータの読み込みに失敗しました。レビューは続けられますが、古いデータはストレージを直すまで見えない場合があります。",
    dismiss: "閉じる",
    footerLoaded:
      "英語を既定表示にしつつ、日本語にも切り替え可能です。いまは自分で登録した miniapp だけを起点にレビューできます。",
    footerLoading: "ローカルのボードデータを読み込み中...",
    inspectManifest: "manifest を確認",
  },
} as const satisfies Record<AppLocale, Record<string, unknown>>;
